---
- name: Create Jira postgres user
  become_user: postgres
  postgresql_user:
    name: "{{ jira_database_username }}"
    password: "{{ jira_database_password }}"
    role_attr_flags: NOCREATEDB,NOSUPERUSER,LOGIN
    state: present

- name: Create a new database for Jira
  become_user: postgres
  postgresql_db:
    name: "{{ jira_database_name }}"
    owner: "{{ jira_database_username }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

