---
dependency:
  name: galaxy
driver:
  name: docker

lint: |
    yamllint .
    ansible-lint .

platforms:
  - name: openjdk-adopt-test
    groups:
      - openjdk
    image: ${DOCKER_IMAGE_BASE:-debian:buster-slim}

provisioner:
  name: ansible
  inventory:
    group_vars:
      openjdk:
        java_open_jdk_home: /usr/lib/jvm/{{ java_open_jdk_home_dir }}
        java_jdk_vendor: adoptopenjdk
        java_open_jdk_version: ${JDK_VERSION}
        java_open_jdk_version_major: ${JDK_MAJOR}

scenario:
  name: adoptopenjdk
verifier:
  name: ansible
