---
galaxy_info:
  role_name: java_role
  author: idealista
  company: Idealista S.A.U.
  description: Java role, install openJDK and set system defaults
  min_ansible_version: 2.8.4.0
  license: Apache 2.0
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: EL
      versions:
        - 7
        - 8
