---
# Variable configuration.

- include_tasks: variables.yml

- include_tasks: setup-8.0.yml
  when: ansible_os_family == 'Debian' and version_mysql_install == '8.0'

- include_tasks: setup-5.7.yml
  when: ansible_os_family == 'Debian' and version_mysql_install == '5.7'

- include_tasks: setup-5.6.yml
  when: ansible_os_family == 'Debian' and version_mysql_install == '5.6'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

#Configure MySQL.
- include_tasks: configure.yml
- include_tasks: secure-installation-5-6.yml
  when: ansible_os_family == 'Debian' and version_mysql_install == '5.6'
- include_tasks: secure-installation-5-7.yml
  when: ansible_os_family == 'Debian' and version_mysql_install == '5.7'
- include_tasks: secure-installation-8-0.yml
  when: ansible_os_family == 'Debian' and version_mysql_install == '8.0'
- include_tasks: databases.yml
- include_tasks: users.yml
- include_tasks: replication.yml
