---
- name: Create Confluence postgres user
  become_user: postgres
  postgresql_user:
    name: "{{ confluence_database_username }}"
    password: "{{ confluence_database_password }}"
    role_attr_flags: NOCREATEDB,NOSUPERUSER,LOGIN
    state: present

- name: Create a new database for Confluence
  become_user: postgres
  postgresql_db:
    name: "{{ confluence_database_name }}"
    owner: "{{ confluence_database_username }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
- debug:
    msg: "{{ confluence_database_password }}"
