---

- name: Java | Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ java_jdk_vendor }}/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

# Using pattern described in Ansible Best Practices and Conventions (Appendix B), Ansible for Devops (p. 406)
# Allowing to 'override' variables that are defined using include_vars
- name: Java | Setting OS specific variables (I)
  set_fact:
    java_open_jdk_version_major: "{{ java_open_jdk_version_major if java_open_jdk_version_major is defined and java_open_jdk_version_major is not sameas None and java_open_jdk_version_major else __java_open_jdk_version_major }}"  # noqa 204
    java_required_repositories_openjdk: "{{ java_required_repositories_openjdk if java_required_repositories_openjdk is defined and java_required_repositories_openjdk is not sameas None and java_required_repositories_openjdk|length else __java_required_repositories_openjdk }}"  # noqa 204
    java_required_key_repositories_openjdk: "{{ java_required_key_repositories_openjdk if java_required_key_repositories_openjdk is defined and java_required_key_repositories_openjdk is not sameas None and java_required_key_repositories_openjdk|length  else __java_required_key_repositories_openjdk }}"  # noqa 204
    java_required_libs_openjdk: "{{ java_required_libs_openjdk if java_required_libs_openjdk is defined and java_required_libs_openjdk is not sameas None and java_required_libs_openjdk|length else __java_required_libs_openjdk }}"  # noqa 204

- name: Java | Setting OS specific variables (II)
  set_fact:
    java_open_jdk_home_dir: "{{ java_open_jdk_home_dir if java_open_jdk_home_dir is defined and java_open_jdk_home_dir is not sameas None and java_open_jdk_home_dir else __java_open_jdk_home_dir }}"  # noqa 204
    java_open_jdk_package: "{{ java_open_jdk_package if java_open_jdk_package is defined and java_open_jdk_package is not sameas None and java_open_jdk_package else __java_open_jdk_package }}"  # noqa 204

- name: Java | Setting specific variables
  set_fact:
    java_home: "{{ java_open_jdk_home }}"

- block:
    - name: Java | Install extra apt tools
      package:
        name: "{{ java_open_jdk_apt_extra_packages }}"
        state: present
      until: apt_tools_installed is succeeded
      register: apt_tools_installed
      retries: 10
      delay: 45
      when: java_open_jdk_apt_extra_packages |length > 0
    - name: Java | add required key repositories, Debian
      apt_key:
        url: "{{ item }}"
        state: present
      with_items: "{{ java_required_key_repositories_openjdk }}"
    - name: Java | Add required repositories, Debian
      apt_repository:
        repo: "{{ item }}"
        state: present
        update_cache: true
      with_items: "{{ java_required_repositories_openjdk }}"
  when: ansible_os_family == 'Debian'

- block:
    - name: Java | Add required key repositories, RedHat
      rpm_key:
        key: "{{ item }}"
        state: present
      with_items: "{{ java_required_key_repositories_openjdk }}"
    - name: Java | Add required repositories, RedHat
      yum_repository:
        name: "{{ item.name }}"
        description: OpenJDK YUM alt repo
        file: "{{ item.name }}.repo"
        baseurl: "{{ item.baseurl }}"
        gpgcheck: true
      with_items: "{{ java_required_repositories_openjdk }}"
  when: ansible_os_family == 'RedHat'

- name: Java | Install required libs
  package:
    name: "{{ java_required_libs_openjdk }}"
    state: present
  until: java_required_libs_installed is succeeded
  register: java_required_libs_installed

- name: Java | Install Java, Debian
  apt:
    name: "{{ ( java_open_jdk_package + '=' + java_open_jdk_version ) if java_open_jdk_version is defined  and java_open_jdk_version is not sameas None else java_open_jdk_package }}"  # noqa 204
    state: present
    update_cache: true
    cache_valid_time: 3600
  until: java_package_installed is succeeded
  register: java_package_installed
  when: ansible_os_family == 'Debian'

- name: Java | Install Java, RedHat
  yum:
    name: "{{ ( java_open_jdk_package + '-' + java_open_jdk_version ) if java_open_jdk_version is defined and java_open_jdk_version is not sameas None else java_open_jdk_package }}"  # noqa 204
    state: present
    update_cache: true
  until: java_package_installed is succeeded
  register: java_package_installed
  when: ansible_os_family == 'RedHat'

- name: Java | Export environment variables
  template:
    src: jdk.sh.j2
    dest: /etc/profile.d/jdk.sh
    mode: 0755
    owner: root
    group: root

- name: Java | Source environment variables
  shell: source /etc/profile
  args:
    executable: /bin/bash
  changed_when: false
  tags:
    - skip_ansible_lint
