---
python_executable: >-
  {{ (ansible_facts.python.version.major|int == 3) | ternary('python3', 'python') }}
mysql_deb_url: https://repo.mysql.com//mysql-apt-config_0.8.18-1_all.deb
mysql_python_packages:
  - '{{ python_executable }}-pip'
  - '{{ python_executable }}-apt'
  - python3-dev
  - gnupg
  - default-libmysqlclient-dev
  - build-essential
mysql_packages:
  - mysql-community-server
  - mysql-community-client 
mysql_daemon: mysqld
mysql_apt_keyserver: pool.sks-keyservers.net
mysql_apt_key_id: 5072E1F5