---
- name: Create jsm postgres user
  become_user: postgres
  postgresql_user:
    name: "{{ jsm_database_username }}"
    password: "{{ jsm_database_password }}"
    role_attr_flags: NOCREATEDB,NOSUPERUSER,LOGIN
    state: present

- name: Create a new database for jsm
  become_user: postgres
  postgresql_db:
    name: "{{ jsm_database_name }}"
    owner: "{{ jsm_database_username }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

