---
# vars file for mssql

mssql_gpgkey: https://packages.microsoft.com/keys/microsoft.asc

mssql_rhel_repositories:
  - name: packages-microsoft-com-mssql-server-{{ mssql_version }}
    description: Microsoft MSSQL server
    baseurl: https://packages.microsoft.com/rhel/7/mssql-server-{{ mssql_version }}/
  - name: packages-microsoft-com-prod
    description: Microsoft tools
    baseurl: https://packages.microsoft.com/rhel/7/prod/

mssql_ubuntu_repositories:
  - repo: https://packages.microsoft.com/ubuntu/{{ansible_distribution_major_version}}.04/prod
  - repo: https://packages.microsoft.com/ubuntu/{{ansible_distribution_major_version}}.04/mssql-server-2019

_mssql_server_package:
  Debian: mssql-server
  RedHat: &redhat_service_package mssql-server
  Rocky: *redhat_service_package
  Amazon: *redhat_service_package

mssql_server_package: "{{ _mssql_server_package[ansible_os_family] }}"

_mssql_server_agent_package:
  Debian: mssql-server-agent
  RedHat: &redhat_server_agent_package mssql-server-agent
  Rocky: *redhat_server_agent_package
  Amazon: *redhat_server_agent_package

mssql_server_agent_package: "{{ _mssql_server_agent_package[ansible_os_family] }}"

mssql_fts_package: mssql-server-fts
