---

  - name: install fail2ban
    apt:
      name:  fail2ban
      state: present
      cache_valid_time: 3600
      update_cache: yes

  - name: push fail2ban jail configuration
    template:
      src:  fail2ban/jail.local.j2
      dest: /etc/fail2ban/jail.local
      mode: 0644

  - name: push fail2ban sendmail configuration
    template:
      src: fail2ban/{{ item }}.j2
      dest: /etc/fail2ban/action.d/{{ item }}
      mode: 0644
    with_items:
      - sendmail.conf
      - sendmail-whois.conf
    notify: restart fail2ban
