---

  - name: install ntp package
    apt:
      name: ntp
      cache_valid_time: 3600
      update_cache: yes

  - name: set time zone
    template:
      src:  ntp/timezone.j2
      dest: /etc/timezone

  - name: configure time zone
    shell: dpkg-reconfigure -f noninteractive tzdata
    tags: [ skip_ansible_lint ]
    args:
      warn: False
    notify:
      - restart cron
