---

# Using pattern described in Ansible Best Practices and Conventions (Appendix B), Ansible for Devops (p. 406)
__java_open_jdk_version_major: 11
# Supported openjdk major releases: 1.8.0, 11

__java_required_repositories_openjdk: []
__java_required_libs_openjdk: []
__java_required_key_repositories_openjdk: []

__java_open_jdk_package: "java-{{ java_open_jdk_version_major }}-openjdk-headless"
__java_open_jdk_home_dir: "jre-{{ java_open_jdk_version_major }}"
